# Privacy config (https://gohugo.io/configuration/privacy/)
# 隐私信息配置 (https://gohugo.io/configuration/privacy/)

# privacy of the Google Analytics (replaced by params.analytics.google)
# Google Analytics 相关隐私 (被 params.analytics.google 替代)
[googleAnalytics]
  # ...
[x]
  enableDNT = true
[youtube]
  privacyEnhanced = true
